[package]
name = "utl"
version = "0.1.0"
authors = ["carado <carado@carado.moe>"]
edition = "2018"

[dependencies]
num-traits = "0.2.12"
derive_more = "0.99"
rustc-hash = "1.1"
fnv = "1.0"
half = "1.6"

