[package]
name = "maps"
version = "0.1.0"
authors = ["carado <carado@carado.moe>"]
edition = "2018"

[lib]
path = "lib.rs"

[features]
default = ["fnv", "rustc-hash"]

[dependencies]
rustc-hash = { version = "1.1", optional = true }
fnv = { verison = "1.0", optional = true }

